README.md
Closes  #52 
Adding links to the new Wiki in the Readme
=> 📝Wiki | Add links to the Readme

components/liveStreamBanner.tsx
=> 🐛  Fix Banner layout shifting

.vscode/extensions.json, components/blocks/aboutUs.tsx, components/blocks/upcomingEvents.tsx, components/layout/analytics.tsx, components/layout/footer.tsx, components/layout/header.tsx, components/layout/layout.tsx, components/testimonials/TestimonialRow.tsx, components/util/container.tsx, components/util/socialIcons.tsx, content/pages/home.mdx, lib/ssw.megamenu/components/menu/index.module.css, next.config.js, pages/_app.tsx, public/robots.txt, styles.css
Related to #59 
closes #73
Improves best practice 🏆
Demo:
https://user-images.githubusercontent.com/600044/215403665-07b588b0-bbef-4d55-a25c-14dc34f964d7.mp4
=> Try improve perf

content/pages/home.mdx
=> 🐛  Fix home page

content/pages/home.mdx, pages/_app.tsx
=> fixed mega menu breaking by importing font awesome styles

.github/actions/deploy/action.yml, .github/workflows/main-build-and-deploy.yml, .github/workflows/pr-push-deploy.yml, infra/appService.bicep
- looks like Azure has kept the AppService from my account around (you can never really delete something off the internet)
- add entropy to name to avoid a collision
closes #53
=> 🤖 appservice - added entropy to appservice name

components/blocks/aboutUs.tsx, components/blocks/booking.tsx, components/blocks/breadcrumbs.tsx, components/blocks/builtOnAzure.tsx, components/blocks/carousel.tsx, components/blocks/clientLogos.tsx, components/blocks/clients.tsx, components/blocks/columnLayout.tsx, components/blocks/customImage.tsx, components/blocks/serviceCards.tsx, components/blocks/upcomingEvents.tsx, components/blocks/videoEmbed.tsx, components/layout/analytics.tsx, components/layout/footer.tsx, components/layout/header.tsx, components/marketing/Marketing.tsx, components/reactPlayer/reactPlayer.tsx, components/technologyCard/technologyCard.tsx, components/testimonials/TestimonialRow.tsx, components/util/actions.tsx, components/util/consulting/benefits.tsx, components/util/socialIcons.tsx, content/consulting/angular.mdx, package.json, pages/404.tsx, pages/_app.tsx, pages/consulting/[filename].tsx, pages/thankyou.tsx, yarn.lock
[✨Upgrade - React 18 + Next.js 13#107](https://github.com/SSWConsulting/SSW.Website-v3/issues/107)
=> 107 upgrade nextjs

Dockerfile
closes #134
no screenshots/videos are applicable to this change
=> ⬆ Docker - use node 18

.github/settings.yml, components/blocks/booking.tsx, components/blocks/clientLogos.tsx, components/bookingButton/bookingButton.tsx, components/bookingForm/bookingForm.tsx, components/popup/popup.tsx, lib/ssw.megamenu/components/menu/index.module.css, pages/consulting/[filename].tsx
#136 
TODO:
**Figure: responsive top module**
**Figure: responsive testimonials**
**Figure: responsive booking button 1**
**Figure: responsive booking button 2**
**Figure: responsive booking button 3**
**Figure: centered companies' logo**
**Figure: Megamenu alignment**
**Figure: Booking form on mobile**
=> 136 fix mobile layout

components/blocks/aboutUs.tsx, components/blocks/columnLayout.tsx, components/blocks/upcomingEvents.tsx, tailwind.config.js
Closes #113 
**Figure: 2 columns on sm breakpoint**
**Figure: Events widget now expand to full screen width on sm breakpoint**
**Figure: Images on column layout now have appropriate widths under md breakpoint**
=> 🐛 Designer Review - Media width problems

content/consulting/power-bi.mdx, content/consulting/smart-office-and-smart-home.mdx, pages/consulting/[filename].tsx
Closes #161
**Figure: Empty space is removed when there's no tech cards**
=> Technology cards - Remove empty space

content/consulting/access-database-upsizing.mdx, content/consulting/artificial-intelligence.mdx, content/consulting/azure-synapse.mdx, content/consulting/blazor.mdx, content/consulting/bots.mdx, content/consulting/chinafy-app.mdx, content/consulting/database-development.mdx, content/consulting/desktop-development.mdx, content/consulting/devops.mdx, content/consulting/enterprise-reporting.mdx, content/consulting/kubernetes.mdx, content/consulting/microsoft-hololens.mdx, content/consulting/mobile-application-development.mdx, content/consulting/pay-per-click.mdx, content/consulting/power-bi.mdx, content/consulting/react.mdx, content/consulting/remote-work.mdx, content/consulting/scrum.mdx, content/consulting/security.mdx, content/consulting/smart-office-and-smart-home.mdx, content/consulting/vue.mdx, content/consulting/web-applications.mdx, content/consulting/xero-myob.mdx
Fixed class name causing text to not highlight correctly
Closes #165
=> 165 Header keyword not red

styles.css
Closes #164, added Tailwind styling for h3 to match previous version
=> Added Tailwind stylings for h3

components/util/socialIcons.tsx
=> 💄Social Icons - make phone icon face the other way

components/bookingForm/bookingForm.tsx, components/form/formGroupTextArea.tsx
=> fixed typo and changed placeholder text

content/consulting/access-database-upsizing.mdx, content/consulting/alm-azure-devops.mdx, content/consulting/angular.mdx, content/consulting/artificial-intelligence.mdx, content/consulting/azure-synapse.mdx, content/consulting/blazor.mdx, content/consulting/bots.mdx, content/consulting/database-development.mdx, content/consulting/desktop-development.mdx, content/consulting/devops.mdx, content/consulting/enterprise-reporting.mdx, content/consulting/microsoft-hololens.mdx, content/consulting/pay-per-click.mdx, content/consulting/react.mdx, content/consulting/scrum.mdx, content/consulting/security.mdx, content/consulting/vue.mdx, content/consulting/web-applications.mdx, content/consulting/xero-myob.mdx, yarn.lock
**Figure: Old implementation**
**Figure: New implementation**
Closes: #201
=> changed technology cards header to 'Related Technologies'

components/blocks/aboutUs.tsx
**Figure: Old text**
**Figure: New changes**
Closes #193
=> changed "Contact Us" text from red to black

content/technologies/angular.mdx, content/technologies/azure-bot.mdx, content/technologies/azure-devops.mdx, content/technologies/cortical-io.mdx, content/technologies/dotnet.mdx, content/technologies/git.mdx, content/technologies/jira.mdx, content/technologies/jquery.mdx, content/technologies/kubernetes.mdx, content/technologies/ms-access.mdx, content/technologies/ms-layout.mdx, content/technologies/ms-remote-assist.mdx, content/technologies/ms-sql-server.mdx, content/technologies/ms-system-center.mdx, content/technologies/node-js.mdx, content/technologies/opencv.mdx, content/technologies/power-bi.mdx, content/technologies/pwa.mdx, content/technologies/pytorch.mdx, content/technologies/react copy.mdx, content/technologies/react-native.mdx, content/technologies/react.mdx, content/technologies/responsive-websites.mdx, content/technologies/visual-studio.mdx, content/technologies/wpf.mdx
**Figure: Technology cards with headers**
Closes #202
=> Added headings to all technology cards

components/layout/layout.tsx, components/util/container.tsx
=> 💄  Make site wider

content/global/index.json
=> 💄 Page Title - add Newcastle

.github/dependabot.yml
- ignored npm: yup
- added github-actions
- added docker
- configured rebase stratregy
- set to weekly
closes #171
=> 🤖 Dependabot - configure more ecosystems

.github/.env, .github/settings.yml, .github/workflows/pr-infra.yml, .github/workflows/update-settings.yml, components/blocks/columnLayout.tsx
=> 🤖 Settings - add PR checks
